# Generated by Django 2.1 on 2020-06-22 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 11, 9, 13, 43486)),
        ),
    ]
