# Generated by Django 2.1 on 2019-08-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve_Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('Party_size', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('charges', models.CharField(max_length=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.Halls')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.HallMeal')),
            ],
            options={
                'db_table': 'reserve_hall',
            },
        ),
    ]
